import { Logger } from '../../utils/logger.js';
import { ResourceTemplate, McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { ReadResourceResult } from '@modelcontextprotocol/sdk/types.js';
import { Variables } from '@modelcontextprotocol/sdk/shared/uriTemplate.js';
import { McpUnityError, ErrorType } from '../../utils/errors.js';
import { getHierarchy } from '../../custom/cache/hierarchyCache.js';

const resourceName = 'cached_scene_hierarchy';
const resourceUri = 'unity://hierarchy/cached/{hierarchyId}';
const resourceMimeType = 'application/json';

export function registerCachedHierarchyResource(server: McpServer, logger: Logger) {
  logger.info(`Registering resource: ${resourceName}`);

  const resourceTemplate = new ResourceTemplate(resourceUri, { list: undefined });

  server.resource(
    resourceName,
    resourceTemplate,
    {
      description: 'Retrieve cached scene hierarchy by ID (generated by get_scenes_hierarchy_compact).',
      mimeType: resourceMimeType,
    },
    async (uri, variables) => {
      try {
        return resourceHandler(uri, variables);
      } catch (error) {
        logger.error(`Error handling resource ${resourceName}: ${error}`);
        throw error;
      }
    }
  );
}

function resourceHandler(uri: URL, variables: Variables): ReadResourceResult {
  const hierarchyId = decodeURIComponent(variables['hierarchyId'] as string);
  const hierarchy = getHierarchy<any>(hierarchyId);

  if (!hierarchy) {
    throw new McpUnityError(
      ErrorType.RESOURCE_FETCH,
      `Cached hierarchy not found for id ${hierarchyId}`
    );
  }

  return {
    contents: [
      {
        uri: `unity://hierarchy/cached/${hierarchyId}`,
        mimeType: resourceMimeType,
        text: JSON.stringify(hierarchy, null, 2),
      },
    ],
  };
}
