import { Logger } from '../../utils/logger.js';
import { ResourceTemplate, McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { ReadResourceResult } from '@modelcontextprotocol/sdk/types.js';
import { Variables } from '@modelcontextprotocol/sdk/shared/uriTemplate.js';
import { McpUnityError, ErrorType } from '../../utils/errors.js';
import { getSession } from '../../custom/cache/sessionCache.js';

const resourceName = 'cached_console_logs';
const resourceUri = 'unity://logs/cached/{sessionId}';
const resourceMimeType = 'application/json';

export function registerCachedLogsResource(server: McpServer, logger: Logger) {
  logger.info(`Registering resource: ${resourceName}`);

  const resourceTemplate = new ResourceTemplate(resourceUri, { list: undefined });

  server.resource(
    resourceName,
    resourceTemplate,
    {
      description: 'Retrieve cached console logs by session ID (generated by get_console_logs_compact).',
      mimeType: resourceMimeType,
    },
    async (uri, variables) => {
      try {
        return resourceHandler(uri, variables);
      } catch (error) {
        logger.error(`Error handling resource ${resourceName}: ${error}`);
        throw error;
      }
    }
  );
}

function resourceHandler(uri: URL, variables: Variables): ReadResourceResult {
  const sessionId = decodeURIComponent(variables['sessionId'] as string);
  const logs = getSession<any[]>(sessionId);

  if (!logs) {
    throw new McpUnityError(
      ErrorType.RESOURCE_FETCH,
      `Cached logs not found for session ${sessionId}`
    );
  }

  return {
    contents: [
      {
        uri: `unity://logs/cached/${sessionId}`,
        mimeType: resourceMimeType,
        text: JSON.stringify(logs, null, 2),
      },
    ],
  };
}
