import { Logger } from '../../utils/logger.js';
import { ResourceTemplate, McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { ReadResourceResult } from '@modelcontextprotocol/sdk/types.js';
import { Variables } from '@modelcontextprotocol/sdk/shared/uriTemplate.js';
import { McpUnityError, ErrorType } from '../../utils/errors.js';
import { getGameObject } from '../../custom/cache/gameObjectCache.js';

const resourceName = 'cached_gameobject';
const resourceUri = 'unity://gameobject/cached/{cacheId}';
const resourceMimeType = 'application/json';

export function registerCachedGameObjectResource(server: McpServer, logger: Logger) {
  logger.info(`Registering resource: ${resourceName}`);

  const resourceTemplate = new ResourceTemplate(resourceUri, { list: undefined });

  server.resource(
    resourceName,
    resourceTemplate,
    {
      description: 'Retrieve cached GameObject details by ID (generated by get_gameobject_compact).',
      mimeType: resourceMimeType,
    },
    async (uri, variables) => {
      try {
        return resourceHandler(uri, variables);
      } catch (error) {
        logger.error(`Error handling resource ${resourceName}: ${error}`);
        throw error;
      }
    }
  );
}

function resourceHandler(uri: URL, variables: Variables): ReadResourceResult {
  const cacheId = decodeURIComponent(variables['cacheId'] as string);
  const gameObject = getGameObject<any>(cacheId);

  if (!gameObject) {
    throw new McpUnityError(
      ErrorType.RESOURCE_FETCH,
      `Cached GameObject not found for id ${cacheId}`
    );
  }

  return {
    contents: [
      {
        uri: `unity://gameobject/cached/${cacheId}`,
        mimeType: resourceMimeType,
        text: JSON.stringify(gameObject, null, 2),
      },
    ],
  };
}
